# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "config.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x0ewhisper_typing"\x12\n\x10GetConfigRequest"=\n\x13UpdateConfigRequest\x12&\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x16.whisper_typing.Config"\xa7\x01\n\x06\x43onfig\x12\r\n\x05model\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompute_type\x18\x04 \x01(\t\x12\x12\n\nuse_ollama\x18\x05 \x01(\x08\x12\x13\n\x0bollama_host\x18\x06 \x01(\t\x12\x17\n\x0fmodel_cache_dir\x18\x07 \x01(\t\x12\x14\n\x0cgemini_model\x18\x08 \x01(\t"G\n\x0e\x43onfigResponse\x12&\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x16.whisper_typing.Config\x12\r\n\x05\x65rror\x18\x02 \x01(\t"+\n\x11ListModelsRequest\x12\x16\n\x0einclude_ollama\x18\x01 \x01(\x08"y\n\tModelInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\t\x12\x12\n\nsize_bytes\x18\x04 \x01(\x03\x12\x15\n\ris_downloaded\x18\x05 \x01(\x08\x12\x0f\n\x07\x62\x61\x63kend\x18\x06 \x01(\t"N\n\x12ListModelsResponse\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.whisper_typing.ModelInfo\x12\r\n\x05\x65rror\x18\x02 \x01(\t"O\n\x11TestConfigRequest\x12&\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x16.whisper_typing.Config\x12\x12\n\ntest_audio\x18\x02 \x01(\x0c"\\\n\x12TestConfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rtranscription\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\xdd\x02\n\rConfigService\x12M\n\tGetConfig\x12 .whisper_typing.GetConfigRequest\x1a\x1e.whisper_typing.ConfigResponse\x12S\n\x0cUpdateConfig\x12#.whisper_typing.UpdateConfigRequest\x1a\x1e.whisper_typing.ConfigResponse\x12S\n\nListModels\x12!.whisper_typing.ListModelsRequest\x1a".whisper_typing.ListModelsResponse\x12S\n\nTestConfig\x12!.whisper_typing.TestConfigRequest\x1a".whisper_typing.TestConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "config_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals["_GETCONFIGREQUEST"]._serialized_start=32
  _globals["_GETCONFIGREQUEST"]._serialized_end=50
  _globals["_UPDATECONFIGREQUEST"]._serialized_start=52
  _globals["_UPDATECONFIGREQUEST"]._serialized_end=113
  _globals["_CONFIG"]._serialized_start=116
  _globals["_CONFIG"]._serialized_end=283
  _globals["_CONFIGRESPONSE"]._serialized_start=285
  _globals["_CONFIGRESPONSE"]._serialized_end=356
  _globals["_LISTMODELSREQUEST"]._serialized_start=358
  _globals["_LISTMODELSREQUEST"]._serialized_end=401
  _globals["_MODELINFO"]._serialized_start=403
  _globals["_MODELINFO"]._serialized_end=524
  _globals["_LISTMODELSRESPONSE"]._serialized_start=526
  _globals["_LISTMODELSRESPONSE"]._serialized_end=604
  _globals["_TESTCONFIGREQUEST"]._serialized_start=606
  _globals["_TESTCONFIGREQUEST"]._serialized_end=685
  _globals["_TESTCONFIGRESPONSE"]._serialized_start=687
  _globals["_TESTCONFIGRESPONSE"]._serialized_end=779
  _globals["_CONFIGSERVICE"]._serialized_start=782
  _globals["_CONFIGSERVICE"]._serialized_end=1131
# @@protoc_insertion_point(module_scope)
