# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import config_pb2 as config__pb2
import grpc

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
         " but the generated code in config_pb2_grpc.py depends on"
         f" grpcio>={GRPC_GENERATED_VERSION}."
         f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
         f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ConfigServiceStub:
    """Configuration service for backend settings management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.

        """
        self.GetConfig = channel.unary_unary(
                "/whisper_typing.ConfigService/GetConfig",
                request_serializer=config__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=config__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                "/whisper_typing.ConfigService/UpdateConfig",
                request_serializer=config__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=config__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                "/whisper_typing.ConfigService/ListModels",
                request_serializer=config__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=config__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.TestConfig = channel.unary_unary(
                "/whisper_typing.ConfigService/TestConfig",
                request_serializer=config__pb2.TestConfigRequest.SerializeToString,
                response_deserializer=config__pb2.TestConfigResponse.FromString,
                _registered_method=True)


class ConfigServiceServicer:
    """Configuration service for backend settings management
    """

    def GetConfig(self, request, context):
        """Get current configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateConfig(self, request, context):
        """Update configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListModels(self, request, context):
        """List available models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TestConfig(self, request, context):
        """Test configuration (verify model loads, test transcription)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            "GetConfig": grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=config__pb2.GetConfigRequest.FromString,
                    response_serializer=config__pb2.ConfigResponse.SerializeToString,
            ),
            "UpdateConfig": grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=config__pb2.UpdateConfigRequest.FromString,
                    response_serializer=config__pb2.ConfigResponse.SerializeToString,
            ),
            "ListModels": grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=config__pb2.ListModelsRequest.FromString,
                    response_serializer=config__pb2.ListModelsResponse.SerializeToString,
            ),
            "TestConfig": grpc.unary_unary_rpc_method_handler(
                    servicer.TestConfig,
                    request_deserializer=config__pb2.TestConfigRequest.FromString,
                    response_serializer=config__pb2.TestConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            "whisper_typing.ConfigService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("whisper_typing.ConfigService", rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigService:
    """Configuration service for backend settings management
    """

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whisper_typing.ConfigService/GetConfig",
            config__pb2.GetConfigRequest.SerializeToString,
            config__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whisper_typing.ConfigService/UpdateConfig",
            config__pb2.UpdateConfigRequest.SerializeToString,
            config__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whisper_typing.ConfigService/ListModels",
            config__pb2.ListModelsRequest.SerializeToString,
            config__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whisper_typing.ConfigService/TestConfig",
            config__pb2.TestConfigRequest.SerializeToString,
            config__pb2.TestConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
