# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import health_pb2 as health__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
         " but the generated code in health_pb2_grpc.py depends on"
         f" grpcio>={GRPC_GENERATED_VERSION}."
         f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
         f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class HealthServiceStub:
    """Health check service for monitoring backend status
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.

        """
        self.Check = channel.unary_unary(
                "/whisper_typing.HealthService/Check",
                request_serializer=health__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=health__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetInfo = channel.unary_unary(
                "/whisper_typing.HealthService/GetInfo",
                request_serializer=health__pb2.InfoRequest.SerializeToString,
                response_deserializer=health__pb2.InfoResponse.FromString,
                _registered_method=True)


class HealthServiceServicer:
    """Health check service for monitoring backend status
    """

    def Check(self, request, context):
        """Check service health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetInfo(self, request, context):
        """Get service information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            "Check": grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=health__pb2.HealthCheckRequest.FromString,
                    response_serializer=health__pb2.HealthCheckResponse.SerializeToString,
            ),
            "GetInfo": grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=health__pb2.InfoRequest.FromString,
                    response_serializer=health__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            "whisper_typing.HealthService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("whisper_typing.HealthService", rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService:
    """Health check service for monitoring backend status
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whisper_typing.HealthService/Check",
            health__pb2.HealthCheckRequest.SerializeToString,
            health__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whisper_typing.HealthService/GetInfo",
            health__pb2.InfoRequest.SerializeToString,
            health__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
