# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import transcription_pb2 as transcription__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
         " but the generated code in transcription_pb2_grpc.py depends on"
         f" grpcio>={GRPC_GENERATED_VERSION}."
         f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
         f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TranscriptionServiceStub:
    """Transcription service for audio-to-text conversion
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.

        """
        self.StreamTranscribe = channel.stream_stream(
                "/whisper_typing.TranscriptionService/StreamTranscribe",
                request_serializer=transcription__pb2.AudioChunk.SerializeToString,
                response_deserializer=transcription__pb2.TranscriptionResponse.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_unary(
                "/whisper_typing.TranscriptionService/Transcribe",
                request_serializer=transcription__pb2.AudioRequest.SerializeToString,
                response_deserializer=transcription__pb2.TranscriptionResponse.FromString,
                _registered_method=True)
        self.ImproveText = channel.unary_unary(
                "/whisper_typing.TranscriptionService/ImproveText",
                request_serializer=transcription__pb2.ImproveTextRequest.SerializeToString,
                response_deserializer=transcription__pb2.ImproveTextResponse.FromString,
                _registered_method=True)


class TranscriptionServiceServicer:
    """Transcription service for audio-to-text conversion
    """

    def StreamTranscribe(self, request_iterator, context):
        """Stream audio chunks and receive transcription results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Transcribe(self, request, context):
        """Single audio file transcription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ImproveText(self, request, context):
        """Improve text using AI (Gemini integration)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            "StreamTranscribe": grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTranscribe,
                    request_deserializer=transcription__pb2.AudioChunk.FromString,
                    response_serializer=transcription__pb2.TranscriptionResponse.SerializeToString,
            ),
            "Transcribe": grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=transcription__pb2.AudioRequest.FromString,
                    response_serializer=transcription__pb2.TranscriptionResponse.SerializeToString,
            ),
            "ImproveText": grpc.unary_unary_rpc_method_handler(
                    servicer.ImproveText,
                    request_deserializer=transcription__pb2.ImproveTextRequest.FromString,
                    response_serializer=transcription__pb2.ImproveTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            "whisper_typing.TranscriptionService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("whisper_typing.TranscriptionService", rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranscriptionService:
    """Transcription service for audio-to-text conversion
    """

    @staticmethod
    def StreamTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/whisper_typing.TranscriptionService/StreamTranscribe",
            transcription__pb2.AudioChunk.SerializeToString,
            transcription__pb2.TranscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whisper_typing.TranscriptionService/Transcribe",
            transcription__pb2.AudioRequest.SerializeToString,
            transcription__pb2.TranscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImproveText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whisper_typing.TranscriptionService/ImproveText",
            transcription__pb2.ImproveTextRequest.SerializeToString,
            transcription__pb2.ImproveTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
