# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcription.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "transcription.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13transcription.proto\x12\x0ewhisper_typing"k\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x10\n\x08is_final\x18\x05 \x01(\x08"m\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\x12\x10\n\x08language\x18\x05 \x01(\t"r\n\x15TranscriptionResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nis_partial\x18\x02 \x01(\x08\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\x12\r\n\x05\x65rror\x18\x05 \x01(\t"3\n\x12ImproveTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\t";\n\x13ImproveTextResponse\x12\x15\n\rimproved_text\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x9c\x02\n\x14TranscriptionService\x12Y\n\x10StreamTranscribe\x12\x1a.whisper_typing.AudioChunk\x1a%.whisper_typing.TranscriptionResponse(\x01\x30\x01\x12Q\n\nTranscribe\x12\x1c.whisper_typing.AudioRequest\x1a%.whisper_typing.TranscriptionResponse\x12V\n\x0bImproveText\x12".whisper_typing.ImproveTextRequest\x1a#.whisper_typing.ImproveTextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "transcription_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals["_AUDIOCHUNK"]._serialized_start=39
  _globals["_AUDIOCHUNK"]._serialized_end=146
  _globals["_AUDIOREQUEST"]._serialized_start=148
  _globals["_AUDIOREQUEST"]._serialized_end=257
  _globals["_TRANSCRIPTIONRESPONSE"]._serialized_start=259
  _globals["_TRANSCRIPTIONRESPONSE"]._serialized_end=373
  _globals["_IMPROVETEXTREQUEST"]._serialized_start=375
  _globals["_IMPROVETEXTREQUEST"]._serialized_end=426
  _globals["_IMPROVETEXTRESPONSE"]._serialized_start=428
  _globals["_IMPROVETEXTRESPONSE"]._serialized_end=487
  _globals["_TRANSCRIPTIONSERVICE"]._serialized_start=490
  _globals["_TRANSCRIPTIONSERVICE"]._serialized_end=774
# @@protoc_insertion_point(module_scope)
